services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HTTP_PORT=8080
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/test?sslmode=disable}
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - JWT_ISSUER=${JWT_ISSUER:-backoffice}
      - JWT_EXPIRY=${JWT_EXPIRY:-12h}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
