name: CI/CD - Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache: true

      - name: Run tests
        run: go test ./...

      - name: Set up Node.js (for Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Require deployment secrets
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: |
          set -euo pipefail
          missing=()
          if [ -z "${RAILWAY_TOKEN:-}" ]; then missing+=("RAILWAY_TOKEN"); fi
          if [ -z "${RAILWAY_SERVICE_ID:-}" ]; then missing+=("RAILWAY_SERVICE_ID"); fi
          if [ ${#missing[@]} -gt 0 ]; then
            printf 'Missing required GitHub secrets: %s\n' "${missing[*]}" >&2
            exit 1
          fi

      - name: Sync environment variables to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_ENVIRONMENT_ID: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
          DATABASE_URL_SECRET: ${{ secrets.RAILWAY_DATABASE_URL }}
          JWT_SECRET_SECRET: ${{ secrets.RAILWAY_JWT_SECRET }}
          JWT_ISSUER_SECRET: ${{ secrets.RAILWAY_JWT_ISSUER }}
        run: |
          set -euo pipefail
          declare -a kvs=()
          if [ -n "${DATABASE_URL_SECRET:-}" ]; then
            kvs+=("DATABASE_URL=${DATABASE_URL_SECRET}")
          fi
          if [ -n "${JWT_SECRET_SECRET:-}" ]; then
            kvs+=("JWT_SECRET=${JWT_SECRET_SECRET}")
          fi
          if [ -n "${JWT_ISSUER_SECRET:-}" ]; then
            kvs+=("JWT_ISSUER=${JWT_ISSUER_SECRET}")
          fi

          if [ ${#kvs[@]} -eq 0 ]; then
            echo "No variables provided; skipping sync."
            exit 0
          fi
          for kv in "${kvs[@]}"; do
            args=(variables set "${kv}")
            if [ -n "${RAILWAY_SERVICE_ID:-}" ]; then
              args+=(--service "${RAILWAY_SERVICE_ID}")
            fi
            if [ -n "${RAILWAY_ENVIRONMENT_ID:-}" ]; then
              args+=(--environment "${RAILWAY_ENVIRONMENT_ID}")
            fi
            railway "${args[@]}"
          done

      - name: Validate Railway variables
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_ENVIRONMENT_ID: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
        run: |
          set -euo pipefail
          list_args=(variables list)
          if [ -n "${RAILWAY_SERVICE_ID:-}" ]; then
            list_args+=(--service "${RAILWAY_SERVICE_ID}")
          fi
          if [ -n "${RAILWAY_ENVIRONMENT_ID:-}" ]; then
            list_args+=(--environment "${RAILWAY_ENVIRONMENT_ID}")
          fi

          vars_output="$(railway "${list_args[@]}")"

          get_args=(variables get)
          if [ -n "${RAILWAY_SERVICE_ID:-}" ]; then
            get_args+=(--service "${RAILWAY_SERVICE_ID}")
          fi
          if [ -n "${RAILWAY_ENVIRONMENT_ID:-}" ]; then
            get_args+=(--environment "${RAILWAY_ENVIRONMENT_ID}")
          fi

          db_candidates=(
            DATABASE_URL
            DATABASE_PUBLIC_URL
            DATABASE_INTERNAL_URL
            DATABASE_EXTERNAL_URL
            DATABASE_URL_NO_SSL
            DATABASE_DIRECT_URL
            POSTGRES_URL
            PGURL
            RAILWAY_DATABASE_URL
            RAILWAY_PUBLIC_URL
          )

          db_found=false
          for key in "${db_candidates[@]}"; do
            value="$(railway "${get_args[@]}" "${key}" 2>/dev/null || true)"
            value="$(printf '%s' "${value}" | tr -d '\r\n')"
            if [ -z "${value}" ]; then
              continue
            fi
            if [ "${key}" = "RAILWAY_PUBLIC_URL" ]; then
              case "${value}" in
                postgres://*|postgresql://*)
                  db_found=true
                  break
                ;;
                *)
                  continue
                ;;
              esac
            else
              db_found=true
              break
            fi
          done

          if [ "${db_found}" != "true" ]; then
            printf 'Railway environment is missing a database connection string.\n' >&2
            printf 'Set one of: %s\n' "${db_candidates[*]}" >&2
            exit 1
          fi

          jwt_value="$(railway "${get_args[@]}" JWT_SECRET 2>/dev/null || true)"
          jwt_value="$(printf '%s' "${jwt_value}" | tr -d '\r\n')"
          if [ -z "${jwt_value}" ]; then
            printf 'Railway environment is missing JWT_SECRET.\n' >&2
            printf 'Add it via Railway Variables UI or provide the RAILWAY_JWT_SECRET GitHub secret.\n' >&2
            exit 1
          fi

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_ENVIRONMENT_ID: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
        run: |
          set -euo pipefail
          args=(up)
          if [ -n "${RAILWAY_SERVICE_ID:-}" ]; then
            args+=(--service "${RAILWAY_SERVICE_ID}")
          fi
          if [ -n "${RAILWAY_ENVIRONMENT_ID:-}" ]; then
            args+=(--environment "${RAILWAY_ENVIRONMENT_ID}")
          fi
          railway "${args[@]}"

      - name: Smoke test public endpoint
        env:
          PUBLIC_BASE_URL: ${{ secrets.RAILWAY_PUBLIC_URL }}
        run: |
          set -euo pipefail
          base_url="${PUBLIC_BASE_URL:-https://api-test-production-2d7d.up.railway.app}"
          echo "Checking ${base_url}/health"
          for attempt in {1..10}; do
            if curl -fsS "${base_url}/health" | grep -Eq '"status"[[:space:]]*:[[:space:]]*"ok"'; then
              echo "Public health check succeeded."
              exit 0
            fi
            echo "Health check attempt ${attempt} failed; retrying in 5s..."
            sleep 5
          done
          echo "Health check failed after multiple attempts." >&2
          exit 1
